import { getSandbox } from "@cloudflare/sandbox";
import { getSandboxOptions } from "@/ai/utils/sandbox";
import { Logger } from "@/lib/logger";
import { getOctokit } from "@services/octokit/core";
import { getGithubToken } from "@utils/secrets";


export interface GitOperation {
    repoUrl: string;
    branch: string;
    changes: Record<string, string>; // path -> content
    commitMessage: string;
}

/**
 * Runs a git operation inside a secure Cloudflare Sandbox.
 * 
 * Flow:
 * 1. Initialize Sandbox
 * 2. Fetch repo default branch via Octokit
 * 3. Clone Repository & Checkout Branch
 * 4. Apply Changes (Write Files)
 * 5. Commit
 * 6. Push using injected GITHUB_TOKEN
 * 7. Open Pull Request
 */
export async function runGitOperation(env: Env, op: GitOperation) {
    const logger = new Logger(env, "Sandbox SDK");
    const logPreface = "[Sandbox SDK: runGitOperation]: ";
    if (!env.SANDBOX) {
        logger.error(`${logPreface} SANDBOX binding not found in Env`);
        throw new Error("SANDBOX binding not found in Env");
    }

    // Parse owner and repo from URL
    const match = op.repoUrl.match(/github\.com\/([^/]+)\/([^/.]+)/);
    if (!match) {
        throw new Error(`Could not parse owner and repo from repoUrl: ${op.repoUrl}`);
    }
    const owner = match[1];
    const repo = match[2];

    logger.info(`${logPreface} Parsed repo: ${owner}/${repo}`);

    // Fetch default branch
    const octokit = await getOctokit(env);
    const { data: repoData } = await octokit.repos.get({ owner, repo });
    const defaultBranch = repoData.default_branch;

    logger.info(`${logPreface} Default branch detected as: ${defaultBranch}`);

    // 1. Init Sandbox
    const id = "engineer-session";
    const options = await getSandboxOptions(env);
    const sandbox = getSandbox(env.SANDBOX as any, id, options);

    logger.info(`${logPreface} Starting Git Operation: ${op.repoUrl} (${op.branch}) on sandbox id: ${id}`);

    try {
        // 2. Clone
        logger.info(`${logPreface} Cloning repo: ${op.repoUrl}...`);
        await (sandbox as any).gitCheckout(op.repoUrl, { branch: op.branch });

        // 3. Apply Changes
        logger.info(`${logPreface} Applying ${Object.keys(op.changes).length} changes...`);
        for (const [path, content] of Object.entries(op.changes)) {
            // Write file relative to workspace root
            await sandbox.writeFile(`/workspace/${path}`, content);
            logger.info(`${logPreface} Wrote file: ${path}`);
        }

        // 4. Commit
        logger.info(`${logPreface} Setting git config and committing...`);

        const gitConfigUsername = 'cd /workspace && git config user.name "AI Engineer"';
        const gitConfigEmail = 'cd /workspace && git config user.email "ai-engineer@cloudflare.com"';
        const gitCommit = `cd /workspace && git commit -am "${op.commitMessage}"`;
        
        await sandbox.exec(gitConfigUsername);
        await sandbox.exec(gitConfigEmail);
        await sandbox.exec(gitCommit);
        
        logger.info(`${logPreface} Changes committed successfully`);
        
        // 5. Push
        logger.info(`${logPreface} Authenticating and pushing branch to remote...`);
        const token = await getGithubToken(env);
        if (!token) {
            throw new Error("No GITHUB_TOKEN found in environment secrets.");
        }
        
        const pushUrl = `https://oauth2:${token}@github.com/${owner}/${repo}.git`;
        await sandbox.exec(`cd /workspace && git remote set-url origin "${pushUrl}"`);
        await sandbox.exec(`cd /workspace && git push -u origin ${op.branch}`);

        logger.info(`${logPreface} Branch ${op.branch} pushed successfully.`);

        // 6. Open PR
        logger.info(`${logPreface} Opening PR against ${defaultBranch}...`);
        const { data: pr } = await octokit.pulls.create({
            owner,
            repo,
            title: op.commitMessage,
            head: op.branch,
            base: defaultBranch,
            body: `Automated PR generated by Colby API.\n\nChanges:\n${Object.keys(op.changes).map(c => `- \`${c}\``).join('\n')}`,
        });

        const message = `Changes applied, pushed, and PR opened: ${pr.html_url}`;
        logger.info(`${logPreface} ${message}`);

        return { status: "success", message, prUrl: pr.html_url };

    } catch (error) {
        logger.error(`${logPreface} Error: ${error}`);
        throw error;
    }
}
