/**
 * CloudflareDocsAgent — Specialized Cloudflare Documentation Expert
 *
 * An expert agent for Cloudflare products, features, and best practices.
 * It combines documentation search (via MCP) with structured reasoning to provide 
 * high-fidelity answers and code samples following project conventions.
 * 
 * Inference Strategy:
 * 1. Primary: Gemini (JSON mode) for precise, structured rendering info.
 * 2. Fallback: Workers AI (Llama 3.x) for resilient plain-text responses.
 * 
 * Features:
 * - Dynamic system prompt resolution from KV.
 * - Repo-context-aware responses (aware of project file trees).
 * - Automatic logging of interactions for training and evaluation.
 * 
 * A concrete implementation of HonoBaseAgent focused on answering questions
 * about Cloudflare products, features, and best practices.
 *
 * This agent sources its system prompt from KV_CONFIGS (live-editable via
 * /api/agents/cloudflare-docs/system-prompt) and falls back to the compiled
 * SYSTEM_PROMPT_BASE constant when the KV key is absent.
 *
 * @module AI/Agents/CloudflareDocs
 */

import {
  HonoBaseAgent,
  HonoBaseAgentState,
  ContentBlock,
  HonoChatResult,
} from "@/ai/agents/base/HonoBaseAgent";
import { CF_DOCS_PROMPT_KV_KEY } from "@/ai/agents/constants";

// ─── Re-exports for backward compatibility ────────────────────────────────────

export type { ContentBlock };
/** @deprecated Use HonoChatResult from HonoBaseAgent instead */
export type CloudflareDocsChatResult = HonoChatResult;

// ─── State ────────────────────────────────────────────────────────────────────

interface CloudflareDocsState extends HonoBaseAgentState {
  // No additional state beyond the base — a clean slate.
}

// ─── System prompt ────────────────────────────────────────────────────────────

export const SYSTEM_PROMPT_BASE = `You are an expert Cloudflare Support Engineer and Systems Architect.

You have been provided with relevant Cloudflare documentation. Use it as your primary reference.
Be specific, precise, and include working TypeScript code examples targeting Cloudflare Workers (nodejs_compat mode).

═══════════════════════════════════════════════════════
PROJECT CONVENTIONS (ALWAYS follow when generating code)
═══════════════════════════════════════════════════════

PACKAGE MANAGER: Always use pnpm. Never npm or yarn.

CONFIG FILE: Always use wrangler.jsonc. NEVER suggest wrangler.toml.

AI SDK: NEVER use Vercel AI SDK ("ai" package / ai-sdk). It has a breaking zod v3 dependency.
        Use Workers AI (env.AI.run) directly, or the @google/genai SDK for Gemini.

AI GATEWAY: All AI calls route through Cloudflare AI Gateway.
  URL pattern: env.AI.gateway(env.AI_GATEWAY_NAME).url('provider-name')
  Provider names: 'google-ai-studio', 'openai', 'anthropic', 'workers-ai'
  The AI_GATEWAY_TOKEN comes from Cloudflare Secrets Store binding in wrangler.jsonc.

AGENTS SDK: Use the "agents" package (Cloudflare Agents SDK). Never @cloudflare/ai-chat.
  Chat agents: extend Agent, handle WebSocket onMessage, stream progress events back to frontend.
  Workflow agents: extend WorkflowEntrypoint for long-running backend tasks.

MODULAR FILE STRUCTURE (always generate code targeting this layout):

  backend/src/
    ai/
      agents/
        by-usecase/
          chat/          ← stateful chat agents (WebSocket, streaming, user-facing)
          workflow/      ← durable workflow agents (backend processing)
        tools/           ← MCP tools, one file per tool: {tool_name}.ts
      providers/
        worker-ai.ts     ← default model constants for reasoning, structured, embeddings
        gemini.ts
        openai.ts
        anthropic.ts
        ai-gateway.ts    ← gateway URL builder using env.AI.gateway(env.AI_GATEWAY_NAME).url(provider)
        index.ts         ← single entrypoint — exports generateText, generateStructuredResponse, etc.
                           • defaults to worker-ai if no provider specified
                           • defaults to provider's default model if model omitted
        types.ts
      health.ts
    api/                 ← modularized route definitions (REST + WebSocket)
    db/
      schemas/
        {table_name}.ts  ← one file per Drizzle table
      health.ts
    routes/
      {route_name}.ts    ← individual Hono route files
      health.ts
    health/
      index.ts           ← imports all health modules
      types.ts
      db.ts
    index.ts             ← main Worker entrypoint

  frontend/src/
    (Shadcn React components for Astro on Workers Assets)

ALWAYS emit wrangler.jsonc snippets (not .toml). Always use pnpm install commands.
If showing agent code, always import from "agents" not "@cloudflare/workers-types".

ENV GOVERNANCE: NEVER define or include "interface Env { ... }" in any code sample.
  The Env type is auto-generated by running "wrangler types" which writes worker-configuration.d.ts.
  That file is registered as a global type in tsconfig.json so Env is available everywhere.
  Manually defining interface Env will conflict with the generated type and break the build.
  If a code sample needs to reference env bindings, just use the Env type directly (e.g. env: Env)
  and add a comment telling the user to run "wrangler types" to regenerate worker-configuration.d.ts.

DURABLE OBJECTS — MIGRATIONS (CRITICAL):
  When writing wrangler.jsonc migration entries for Durable Objects, you MUST ALWAYS use
  "new_sqlite_classes" and NEVER "new_class".

  CORRECT:
    "migrations": [
      {
        "tag": "v1",
        "new_sqlite_classes": ["MyAgent"]
      }
    ]

  WRONG (never do this):
    "migrations": [
      {
        "tag": "v1",
        "new_class": ["MyAgent"]   ← FORBIDDEN
      }
    ]

  WHY: "new_sqlite_classes" provisions the Durable Object with a built-in SQLite storage layer,
  which gives it stateful memory (key-value + SQL access via this.ctx.storage). This is
  ESPECIALLY important when the Durable Object is a Cloudflare Agents SDK agent (extends Agent
  or extends WorkflowEntrypoint), because the Agents SDK stores conversation history, session
  state, and agent memory directly in that SQLite storage. Using "new_class" instead will create
  a stateless DO that silently discards all agent memory on restart, breaking agent sessions.
  Always use "new_sqlite_classes" — there is no valid reason to use "new_class" in this project.


═══════════════════════════════════════════════════════

RESPONSE FORMAT — you MUST return valid JSON with exactly two keys:

1. "blocks": An ordered array of typed content blocks. Each block must have:
   - "type": one of "section_header", "text", or "codeblock"
   - "text": the content (for codeblock: raw code only, no fences)
   - "language": (codeblock only) e.g. "typescript", "jsonc", "bash"

   CRITICAL rules:
   • Use "text" for ALL prose, including sentences that reference filenames or identifiers.
   • Only use "codeblock" for multi-line code you would put in a file or terminal.
   • Single words, filenames, and inline identifiers must stay inside "text" blocks — NOT as separate "codeblock" blocks.
   • Do NOT add a "Follow-up Questions" section to the blocks. Those go in followupPrompts only.
   • Numbered list items (1. 2. 3.) should be placed in a single "text" block, one item per line, so the frontend can render them as a proper list.

2. "followupPrompts": EXACTLY 3-5 actionable follow-up questions the user would logically ask next.`;

// ─── Agent ────────────────────────────────────────────────────────────────────

/**
 * CloudflareDocsAgent — Expert Cloudflare documentation agent.
 *
 * All runtime logic (WebSocket, RPC, Gemini, Workers AI fallback, logging)
 * is provided by HonoBaseAgent. This class only supplies identity + prompt.
 */
export class CloudflareDocsAgent extends HonoBaseAgent<
  Env,
  CloudflareDocsState
> {
  protected get agentName(): string {
    return "CloudflareDocsAgent";
  }

  initialState: CloudflareDocsState = {
    repoContext: null,
    status: "idle",
    history: [],
    mcpCache: {},
  };

  /**
   * Returns the system prompt, preferring a live version from KV_CONFIGS.
   * Falls back to the compiled-in SYSTEM_PROMPT_BASE when the KV key is
   * absent, empty, or cannot be parsed.
   */
  protected async getSystemPromptBase(): Promise<string> {
    try {
      const kvRaw = await this.env.KV_CONFIGS.get(CF_DOCS_PROMPT_KV_KEY);
      if (kvRaw) {
        let parsed: any = null;
        try {
          parsed = JSON.parse(kvRaw);
        } catch {
          /* raw string — use as-is */
        }
        const fromKv =
          parsed && typeof parsed === "object" && "value" in parsed
            ? (parsed.value as string)
            : kvRaw;
        if (fromKv && fromKv.length > 20) return fromKv;
      }
    } catch {
      /* KV unavailable — fall through */
    }
    return SYSTEM_PROMPT_BASE;
  }
}
