import { createAgent, tool } from 'honidev';
import { z } from 'zod';

const agentObj = createAgent({
  name: 'jules-overseer',
  model: 'claude-3-5-sonnet-latest',
  system: 'You are the Jules Overseer. You monitor code generated by Jules, review it against Cloudflare standards and user rules, create GitHub PRs, and autonomously merge them if all checks pass.',
  binding: 'JULES_OVERSEER_DO',
  memory: {
    enabled: true,
    episodic: { enabled: true, binding: 'DB' }
  },
  observability: {
    aiGateway: { accountId: "core-gateway", gatewayId: "core-gateway" }
  },
  tools: [
    tool({
      name: 'review_code_output',
      description: 'Review Jules code output against standardization rules',
      input: z.object({ prNumber: z.number().optional(), repo: z.string(), codePayload: z.string() }) as any,
      handler: async ({ prNumber, repo, codePayload }, ctx) => {
        // Validation logic here
        return { approved: true, violations: [] };
      }
    }),
    tool({
      name: 'merge_pull_request',
      description: 'Merge a validated pull request autonomously',
      input: z.object({ prNumber: z.number(), repo: z.string() }) as any,
      handler: async ({ prNumber, repo }, ctx) => {
        // Trigger Github MCP merge
        return { merged: true, prNumber };
      }
    })
  ]
});

export class JulesOverseerDO extends agentObj.DurableObject {}
export const julesOverseerHandler = agentObj.fetch;
