/**
 * @file EngineerAgent/methods/sandbox/git/commit.ts
 * @description Absorbed from SandboxAgent.ts — Cloudflare Sandbox SDK operations.
 *              All methods are pure functions receiving dependencies via DI.
 */
import { getSandbox } from "@cloudflare/sandbox";
import { getGitHubPrivateKey } from "@/utils/secrets";
import { Logger } from "@/lib/logger";

/**
 * Commits changes to a GitHub repository and creates a pull request.
 * @param deps - Sandbox dependencies
 * @param repoUrl - URL of the repository
 * @param sessionId - Session ID for the sandbox
 * @param options - Optional parameters for the commit and pull request
 * @returns Promise with the result of the operation
 */
export async function gitCommitAndPR(
  env: Env,
  repoUrl: string,
  sessionId: string,
  options?: { branch?: string; targetDir?: string; commitMessage?: string; baseBranch?: string }
): Promise<{ success: boolean; message?: string; error?: string; prUrl?: string; prNumber?: number }> {
  const sandbox = getSandbox(env.SANDBOX, sessionId);
  const logger = new Logger(env, "SandboxSDK - gitCommit:");
  const loggerPrefix = `[SandboxSDK - gitCommit - ${sessionId}]`;

  try {
    // 1. Parse repository owner and name from the URL
    const match = repoUrl.match(/github\.com\/([^/]+)\/([^/.]+)/);
    if (!match) {
      throw new Error(`Invalid GitHub URL: ${repoUrl}`);
    }
    
    const [, owner, repo] = match;
    const dir = options?.targetDir ?? "repo";
    const branchName = options?.branch ?? `ai-builder/update-${Date.now()}`;
    const commitMsg = options?.commitMessage ?? "Automated update by AI-Builder";

    logger.info(`${loggerPrefix} Preparing to commit and push to ${owner}/${repo} on branch ${branchName}`);

    // 2. Retrieve GitHub Token
    const githubToken = await getGitHubPrivateKey(env);
    if (!githubToken) {
      throw new Error("GitHub token not found in environment.");
    }

    // 3. Configure Git Identity
    await sandbox.exec(`cd ${dir} && git config user.name "AI-Builder"`);
    await sandbox.exec(`cd ${dir} && git config user.email "core-github-api@hacolby.app"`);

    // 4. Verify if there are actual changes to commit
    const status = await sandbox.exec(`cd ${dir} && git status --porcelain`);
    if (!status.stdout.trim()) {
      logger.info(`${loggerPrefix} No changes to commit.`);
      return { success: true, message: "No changes to commit." };
    }

    // 5. Checkout new branch, stage all files, and commit
    await sandbox.exec(`cd ${dir} && git checkout -b ${branchName}`);
    await sandbox.exec(`cd ${dir} && git add .`);
    
    const commitRes = await sandbox.exec(`cd ${dir} && git commit -m "${commitMsg.replace(/"/g, '\\"')}"`);
    if (!commitRes.success) {
      throw new Error(`Commit failed: ${commitRes.stderr || commitRes.stdout}`);
    }

    // 6. Push the new branch to GitHub
    const pushUrl = `https://${githubToken}@github.com/${owner}/${repo}.git`;
    logger.info(`${loggerPrefix} Pushing branch ${branchName}`);
    
    const pushRes = await sandbox.exec(`cd ${dir} && git push ${pushUrl} ${branchName}`);
    if (!pushRes.success) {
      throw new Error(`Push failed: ${pushRes.stderr || pushRes.stdout}`);
    }

    // 7. Determine the base branch (e.g., main or master) using the GitHub API
    let baseBranch = options?.baseBranch;
    if (!baseBranch) {
      const repoInfoRes = await fetch(`https://api.github.com/repos/${owner}/${repo}`, {
        headers: {
          Authorization: `Bearer ${githubToken}`,
          "User-Agent": "AI-Builder-Sandbox",
          Accept: "application/vnd.github.v3+json",
        },
      });
      
      if (!repoInfoRes.ok) {
        throw new Error(`Failed to fetch repo info to determine default branch: ${await repoInfoRes.text()}`);
      }
      
      const repoInfo = await repoInfoRes.json() as any;
      baseBranch = repoInfo.default_branch || "main";
    }

    // 8. Create the Pull Request
    logger.info(`${loggerPrefix} Creating pull request to ${baseBranch}`);
    const prRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls`, {
      method: "POST",
      headers: {
        Authorization: `Bearer ${githubToken}`,
        "User-Agent": "AI-Builder-Sandbox",
        Accept: "application/vnd.github.v3+json",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        title: commitMsg,
        head: branchName,
        base: baseBranch,
        body: "Automated Pull Request generated by AI-Builder Sandbox.",
      }),
    });

    if (!prRes.ok) {
      const prErr = await prRes.text();
      throw new Error(`Failed to create PR: ${prErr}`);
    }

    const prData = await prRes.json() as any;
    const prNumber = prData?.number ?? null;
    let prUrl = prData?.html_url;

    if((!prUrl || !prUrl.includes(`https://github.com/${owner}/${repo}/pull/`)) && prNumber) {
      logger.info(`${loggerPrefix} "prData?.html_url" is not a valid url (${prUrl}); building a custom pr link using "prData?.number" (${prNumber})`);
      prUrl = `https://github.com/${owner}/${repo}/pull/${prNumber}`;
    }
    logger.info(`${loggerPrefix} PR created successfully: ${prUrl}`);

    return { 
      success: true, 
      message: `Committed and opened PR: ${prUrl}`,
      prUrl,
      prNumber
    };

  } catch (error: any) {
    logger.error(`${loggerPrefix} Failed to commit and PR: ${JSON.stringify(error)}`);
    return { 
        success: false, 
        error: error.message 
    };
  }
}