#!/usr/bin/env python3
"""
Integration test for the deployed Cloudflare Worker GitHub Proxy.

✅ Uses the deployed endpoint at https://core-github-api.hacolby.workers.dev
✅ No GitHub token needed — Worker handles authentication internally.
✅ Exercises /api, /mcp, and /a2a routes:
   - REST GET / POST
   - GraphQL
   - File upsert
   - Issue creation
   - PR creation

Usage:
    python3 test_worker_proxy_public.py
"""

import base64
import requests
from pprint import pprint

BASE_URL = "https://core-github-api.hacolby.workers.dev"
OWNER = "jmbish04"
REPO = "github-worker"
HEADERS = {"Accept": "application/json", "Content-Type": "application/json"}

def run_request(method, url, payload=None):
    print(f"\n🔹 {method.upper()} {url}")
    func = getattr(requests, method)
    r = func(url, headers=HEADERS, json=payload)
    print(f"Status: {r.status_code} {r.reason}")
    try:
        data = r.json()
        pprint(data)
    except Exception:
        print(r.text)
    return r

def test_prefix(prefix: str):
    print(f"\n================= TESTING {prefix.upper()} ================")

    # 1️⃣ REST GET
    run_request(
        "get",
        f"{BASE_URL}/{prefix}/octokit/rest/repos/get?owner={OWNER}&repo={REPO}"
    )

    # 2️⃣ REST POST
    run_request(
        "post",
        f"{BASE_URL}/{prefix}/octokit/rest/repos/create_fork",
        {"owner": OWNER, "repo": REPO}
    )

    # 3️⃣ GraphQL query
    run_request(
        "post",
        f"{BASE_URL}/{prefix}/octokit/graphql",
        {"query": "{ viewer { login } }"}
    )

    # 4️⃣ File upsert
    run_request(
        "post",
        f"{BASE_URL}/{prefix}/tools/files/upsert",
        {
            "owner": OWNER,
            "repo": REPO,
            "path": f"test_{prefix}.txt",
            "content": base64.b64encode(f"Hello from {prefix}".encode()).decode(),
            "message": f"test({prefix}): file upsert via worker proxy"
        },
    )

    # 5️⃣ Issue creation
    run_request(
        "post",
        f"{BASE_URL}/{prefix}/tools/issues/create",
        {
            "owner": OWNER,
            "repo": REPO,
            "title": f"Integration test issue ({prefix})",
            "body": f"Created by automated test suite for {prefix.upper()} route.",
            "labels": ["integration", prefix]
        },
    )

    # 6️⃣ PR creation
    run_request(
        "post",
        f"{BASE_URL}/{prefix}/tools/prs/open",
        {
            "owner": OWNER,
            "repo": REPO,
            "head": "feature-branch",
            "base": "main",
            "title": f"Integration Test PR ({prefix})",
            "body": f"Auto-generated by test suite for {prefix.upper()} route."
        },
    )

def main():
    print("🚀 Running full integration tests against deployed Worker…\n")
    for p in ["api", "mcp", "a2a"]:
        test_prefix(p)
    print("\n✅ Completed all route group tests.")

if __name__ == "__main__":
    main()
