/**
 * @file backend/src/db/schemas/jules/webhook-events.ts
 * @description D1 (SQLite/Drizzle) schema for inbound Jules webhook events.
 *
 * Jules is instructed to call back to this Worker via two endpoints:
 *   - POST /api/webhooks/jules/event  — lifecycle events (blocked, done, etc.)
 *   - POST /api/webhooks/jules/status — incremental progress updates
 *
 * Every payload received from Jules is recorded here for:
 *   - Audit trail and debugging
 *   - Frontend live-feed via WebSocket broadcast
 *   - Agent context retrieval ("remember how Jules got stuck on X")
 *
 * @module DB/Schemas/Jules
 */

import { integer, sqliteTable, text, index } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";

// ─── jules_webhook_events ─────────────────────────────────────────────────────

/**
 * Audit log of every inbound webhook event received from Jules.
 *
 * Event types:
 *   - blocked       : Jules is stuck and cannot proceed
 *   - needs_context : Jules requires additional information
 *   - ready_for_pr  : Jules has finished and is ready for PR creation
 *   - done          : Session marked complete by Jules
 *   - progress      : Incremental status update (called frequently)
 *   - info          : Informational message, no action required
 */
export const julesWebhookEvents = sqliteTable(
  "jules_webhook_events",
  {
    /** UUID primary key generated by the Worker on receipt. */
    id: text("id").primaryKey(),

    /**
     * Jules session ID this event belongs to.
     * References `jules_sessions.id` logically (no FK enforced in SQLite for perf).
     */
    julesSessionId: text("jules_session_id").notNull(),

    /**
     * Classification of the event reported by Jules.
     *
     * - "progress"    — frequent update during task execution
     * - "blocked"     — Jules is waiting and cannot self-unblock
     * - "needs_context" — Jules needs clarification from the originating agent
     * - "ready_for_pr"  — work complete, PR ready for review
     * - "done"        — session concluded (terminal)
     * - "info"        — informational, no action needed
     */
    eventType: text("event_type", {
      enum: [
        "progress",
        "blocked",
        "needs_context",
        "ready_for_pr",
        "done",
        "info",
      ],
    }).notNull(),

    /** Jules-generated human-readable message accompanying the event. */
    message: text("message").notNull(),

    /**
     * Optional completion percentage (0–100) for progress events.
     * Null for non-progress event types.
     */
    progressPct: integer("progress_pct"),

    /**
     * Optional name of the current work step (e.g. "Implementing auth middleware").
     * Primarily populated in progress events.
     */
    stepName: text("step_name"),

    /** Raw JSON payload as received from Jules, stored for audit and debugging. */
    rawPayload: text("raw_payload"),

    /**
     * Timestamp when the Worker finished handling (routing) this event.
     * Null if the event is still being processed or was informational-only.
     */
    handledAt: integer("handled_at", { mode: "timestamp" }),

    /**
     * Identifier of the agent/system that handled this event.
     * E.g., "JulesOverseer", "WorkshopAgent", "alerts-system".
     */
    handledBy: text("handled_by"),

    /** Timestamp when the event was received and stored. */
    createdAt: integer("created_at", { mode: "timestamp" })
      .notNull()
      .default(sql`(strftime('%s', 'now'))`),
  },
  (table) => ({
    sessionIdx: index("jwh_session_idx").on(table.julesSessionId),
    eventTypeIdx: index("jwh_event_type_idx").on(table.eventType),
    createdIdx: index("jwh_created_idx").on(table.createdAt),
  })
);

export type JulesWebhookEvent = typeof julesWebhookEvents.$inferSelect;
export type InsertJulesWebhookEvent = typeof julesWebhookEvents.$inferInsert;
