/**
 * @file backend/src/db/schemas/agents/cloudflare-docs-interactions.ts
 * @description D1 table: one row per chat turn across all Cloudflare Docs Agent surfaces.
 */
import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";

export const cloudflareDoscInteractions = sqliteTable("cloudflare_docs_interactions", {
  /** Auto-increment primary key */
  id: integer("id").primaryKey({ autoIncrement: true }),

  /** UUID shared across all turns of a single chat session */
  sessionId: text("session_id").notNull(),

  /** Originating surface: "global-tools" | "project-tools" | "pr" | "api" */
  source: text("source").notNull(),

  /** GitHub repo URL (if provided by the user or locked by context) */
  githubUrl: text("github_url"),

  /** Raw user message */
  userPrompt: text("user_prompt").notNull(),

  /** Rewritten query sent to the Cloudflare Docs MCP */
  mcpQuery: text("mcp_query"),

  /** Raw response from the Cloudflare Docs MCP (truncated to 4000 chars) */
  mcpResponse: text("mcp_response"),

  /** Final AI response returned to the user (markdown) */
  responseSent: text("response_sent").notNull(),

  /** JSON array of follow-up prompts generated by the AI */
  followUpPrompts: text("follow_up_prompts"),

  /** AI provider: "google-ai-studio" | "workers-ai" | "none" */
  provider: text("provider"),

  /** Specific model used: e.g. "gemini-2.5-flash" or "@cf/meta/llama-3.3-70b-instruct-fp8-fast" */
  modelUsed: text("model_used"),

  /** Error message if inference or MCP calls failed (null on success) */
  error: text("error"),

  /** ISO8601 timestamp */
  createdAt: text("created_at").notNull(),
});

// env.DB_WEBHOOKS env.DB
