-- ============================================================
-- seed_project_tasks.sql
-- Generated: 2026-03-30 01:53:43 UTC
-- Source:    project_tasks.json
-- Tables:    pm_projects, pm_epics, pm_stories, pm_tasks
-- Strategy:  INSERT OR IGNORE (idempotent — safe to re-run)
-- ============================================================

PRAGMA foreign_keys = OFF;

-- ──────────────────────────────────────────────
-- pm_projects  (1 rows)
-- ──────────────────────────────────────────────
INSERT OR IGNORE INTO pm_projects (id, workspace_id, title, description, status, created_at, updated_at) VALUES ('proj-learning-engine-001', 'jmbish04/core-github-api', 'AI Learning & Pattern Recognition Engine', 'A continuous improvement service that extracts all AI coding conversations (Jules, Gemini, Stitch), enriches them with Cloudflare Docs context, identifies recurring failure patterns, and automatically submits PRs to core-github-standardization to immunize future agents against known mistakes.', 'in_progress', 1774835623, 1774835623);

-- ──────────────────────────────────────────────
-- pm_epics  (8 rows)
-- ──────────────────────────────────────────────
INSERT OR IGNORE INTO pm_epics (id, project_id, title, description, status, priority, created_at, updated_at) VALUES ('epic-001-schema', 'proj-learning-engine-001', 'Database Schema — Learning Micro-Domain', 'Create all 10 Drizzle ORM schema files for the learning domain under backend/src/db/schemas/github/learning/. Reuse existing app/tags.ts — no duplicate tags table.', 'todo', 'high', 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_epics (id, project_id, title, description, status, priority, created_at, updated_at) VALUES ('epic-002-ingestion', 'proj-learning-engine-001', 'Learning Ingestion Service', 'Port log_conversations.py logic into a TypeScript LearningIngestionService. Sources: Jules SDK (JulesService), GitHub Octokit (getOctokit), Stitch MCP. Deduplication via sourceIdentifier unique index.', 'todo', 'high', 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_epics (id, project_id, title, description, status, priority, created_at, updated_at) VALUES ('epic-003-agent', 'proj-learning-engine-001', 'LearningAgent Durable Object', 'Stateful Durable Object agent with Contemplation Gate (anti-light-switch). Tools: enrichMessage (CF Docs), tagMessage, analyzeMessage (Workers AI), createInsight, contemplateFix (Vectorize + D1 reflection), submitImprovementPr, issueRemediationComment.', 'todo', 'high', 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_epics (id, project_id, title, description, status, priority, created_at, updated_at) VALUES ('epic-004-workflow', 'proj-learning-engine-001', 'Cloudflare Workflow + Daily Cron', 'LearningWorkflow using Cloudflare Workflows product for durable step execution. Daily cron at 0 6 * * * UTC. Manual trigger via POST /api/learning/sync.', 'todo', 'medium', 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_epics (id, project_id, title, description, status, priority, created_at, updated_at) VALUES ('epic-005-api', 'proj-learning-engine-001', 'API Routes', 'Hono OpenAPI routes at /api/learning/ for sync trigger, session listing, insight search/filter, global standardization score, and upscale endpoint for Jules orchestration.', 'todo', 'medium', 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_epics (id, project_id, title, description, status, priority, created_at, updated_at) VALUES ('epic-006-interceptor', 'proj-learning-engine-001', 'Active PR Interceptor (Real-time Remediation)', 'Webhook-driven interceptor that fires on PR opened/synchronize events. Scans PR diff against known ai_insights patterns and posts remediation comments via user-persona token. Includes D1-backed merge queue for post-merge template hardening.', 'todo', 'medium', 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_epics (id, project_id, title, description, status, priority, created_at, updated_at) VALUES ('epic-007-frontend', 'proj-learning-engine-001', 'Frontend Control Plane (Astro + Dark Shadcn)', '4 Astro pages under frontend/src/pages/learning/: dashboard (Recharts trendlines), sessions (Shadcn Table audit log), board (kibo-ui Kanban: DETECTED→IN_VERIFICATION→IMMUNIZED), showcase (Standardization library + Upscale button).', 'todo', 'low', 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_epics (id, project_id, title, description, status, priority, created_at, updated_at) VALUES ('epic-008-health', 'proj-learning-engine-001', 'Health Monitoring', 'Add /health/learning endpoint to existing health suite. Monitor AI Gateway latency, Sandbox SDK container availability, last successful learning run timestamp, open insight PR count.', 'todo', 'low', 1774835623, 1774835623);

-- ──────────────────────────────────────────────
-- pm_stories  (20 rows)
-- ──────────────────────────────────────────────
INSERT OR IGNORE INTO pm_stories (id, epic_id, title, description, status, priority, created_at, updated_at) VALUES ('story-001-01', 'epic-001-schema', 'Create 10 Drizzle schema files', 'One file per table: sessions.ts, threads.ts, messages.ts, enrichment.ts, tagMapping.ts, aiInsights.ts, aiInsightMessages.ts, aiInsightPrs.ts, aiInsightPrMapping.ts, aiPrReflections.ts. Each exported with Zod OpenAPI schemas.', 'todo', 'high', 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_stories (id, epic_id, title, description, status, priority, created_at, updated_at) VALUES ('story-001-02', 'epic-001-schema', 'Wire schema barrel and run migration', 'Create learning/index.ts barrel. Add ''export * from ./learning'' to backend/src/db/schemas/github/index.ts. Run npm run migrate:db and verify 10 new learning_* tables in D1.', 'todo', 'high', 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_stories (id, epic_id, title, description, status, priority, created_at, updated_at) VALUES ('story-002-01', 'epic-002-ingestion', 'Jules ingestion', 'Use existing JulesService from backend/src/services/julius/jules.ts. List all sessions + activities. Map session → learning_threads (source: jules), activities → learning_messages. Dedup by sourceIdentifier unique index.', 'todo', 'high', 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_stories (id, epic_id, title, description, status, priority, created_at, updated_at) VALUES ('story-002-02', 'epic-002-ingestion', 'GitHub PR ingestion', 'Use getOctokit() from backend/src/services/octokit/core.ts. Search merged PRs by jmbish04. Fetch PR body + issue comments + review comments. Map PR → thread, comments → messages. Dedup by PR URL.', 'todo', 'high', 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_stories (id, epic_id, title, description, status, priority, created_at, updated_at) VALUES ('story-002-03', 'epic-002-ingestion', 'Stitch ingestion', 'Call Stitch MCP paginated API (mirrors _sync_stitch from log_conversations.py). Map project/screen → thread, prompts → messages. Dedup by stitch/{projectId}/{screenName}.', 'todo', 'medium', 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_stories (id, epic_id, title, description, status, priority, created_at, updated_at) VALUES ('story-003-01', 'epic-003-agent', 'Core agent tools: enrich, tag, analyze', 'Implement enrichMessage (CF Docs MCP → learning_enrichment), tagMessage (query app.tags → learning_tag_mapping, createTag if new), analyzeMessage (Workers AI → messages.aiAnalysis). All inference via AI Gateway.', 'todo', 'high', 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_stories (id, epic_id, title, description, status, priority, created_at, updated_at) VALUES ('story-003-02', 'epic-003-agent', 'Pattern detection and insight creation', 'Group threads by category. If 3+ threads share the same correction pattern → createInsight (learning_ai_insights, status: PENDING). Link messages via learning_ai_insight_messages for audit traceability.', 'todo', 'high', 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_stories (id, epic_id, title, description, status, priority, created_at, updated_at) VALUES ('story-003-03', 'epic-003-agent', 'Contemplation Gate (anti-light-switch)', 'Before submitting any PR: query VECTORIZE_INDEX for semantic similarity to prior patterns. Query ai_pr_reflections for prior outcomes. If category was already addressed and deemed successful → skip. If FAILED → escalate to UPGRADE_TEMPLATE target (core-github-standardization).', 'todo', 'high', 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_stories (id, epic_id, title, description, status, priority, created_at, updated_at) VALUES ('story-003-04', 'epic-003-agent', 'Signal-driven vectorization', 'Only vectorize messages with ai_analysis populated OR linked to an ai_insight. Vectorize into VECTORIZE_INDEX binding. Do NOT vectorize every raw prompt — prevents noise in semantic search.', 'todo', 'medium', 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_stories (id, epic_id, title, description, status, priority, created_at, updated_at) VALUES ('story-004-01', 'epic-004-workflow', 'LearningWorkflow class', 'Create backend/src/workflows/learning.ts following pattern from backend/src/workflows/health.ts. Steps: createSession, ingestConversations, runAnalysis, finalizeSession. Each step has timeout + retry.', 'todo', 'medium', 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_stories (id, epic_id, title, description, status, priority, created_at, updated_at) VALUES ('story-004-02', 'epic-004-workflow', 'Register workflow and cron in wrangler.jsonc', 'Add to workflows array: { name: learning-workflow, class_name: LearningWorkflow, binding: LEARNING_WORKFLOW }. Add to triggers.crons: ''0 6 * * *''.', 'todo', 'medium', 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_stories (id, epic_id, title, description, status, priority, created_at, updated_at) VALUES ('story-005-01', 'epic-005-api', 'Core learning routes', 'POST /api/learning/sync (manual trigger → dispatch LearningWorkflow), GET /api/learning/sessions, GET /api/learning/insights (filter by category/status/q), GET /api/learning/insights/:id.', 'todo', 'medium', 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_stories (id, epic_id, title, description, status, priority, created_at, updated_at) VALUES ('story-005-02', 'epic-005-api', 'Upscale and global insights routes', 'GET /api/learning/insights/global (aggregated Standardization Score per category). POST /api/learning/upscale (fetch standardization files + start Jules session for active repo audit).', 'todo', 'medium', 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_stories (id, epic_id, title, description, status, priority, created_at, updated_at) VALUES ('story-006-01', 'epic-006-interceptor', 'PR webhook interceptor', 'Wire learning-interceptor.ts into existing PR webhook handlers (backend/src/automations/pr/). On PR opened/synchronize: scan diff vs known ai_insights patterns. If match → post comment via user-persona GH token targeting assigned agent.', 'todo', 'medium', 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_stories (id, epic_id, title, description, status, priority, created_at, updated_at) VALUES ('story-006-02', 'epic-006-interceptor', 'Post-merge template hardening queue', 'After PR merge webhook: check if merged PR was flagged in learning_ai_insight_prs. If yes → trigger Jules session to apply fix to core-github-standardization. Use D1 mergeQueueStatus field to prevent duplicate triggers.', 'todo', 'medium', 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_stories (id, epic_id, title, description, status, priority, created_at, updated_at) VALUES ('story-007-01', 'epic-007-frontend', '/learning/dashboard — Trendlines', 'Recharts line chart: ''Manual Corrections per PR'' vs ''Immunized Rules'' over time. Queries learning_sessions aggregated data. Dark Shadcn theme.', 'todo', 'low', 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_stories (id, epic_id, title, description, status, priority, created_at, updated_at) VALUES ('story-007-02', 'epic-007-frontend', '/learning/sessions — Audit Log', 'Shadcn Table of analysis runs. Expandable Collapsible rows → threads → enrichment → CF Docs grounding responses → ai_analysis per message.', 'todo', 'low', 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_stories (id, epic_id, title, description, status, priority, created_at, updated_at) VALUES ('story-007-03', 'epic-007-frontend', '/learning/board — Insight Kanban', 'kibo-ui Kanban board mapping learning_ai_insights.status: DETECTED (PENDING) → IN_VERIFICATION → IMMUNIZED. Drag-and-drop updates status via PATCH /api/learning/insights/:id.', 'todo', 'low', 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_stories (id, epic_id, title, description, status, priority, created_at, updated_at) VALUES ('story-007-04', 'epic-007-frontend', '/learning/showcase — Standards Library + Upscale', 'Grid of Shadcn Cards for every standard in core-github-standardization (tsconfig.json, AGENTS.md, /health/index.ts, etc). Each card: ''View Content'' dialog (fetches raw file from GitHub) + ''Upscale Current Repo'' primary button → POST /api/learning/upscale.', 'todo', 'low', 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_stories (id, epic_id, title, description, status, priority, created_at, updated_at) VALUES ('story-008-01', 'epic-008-health', '/health/learning endpoint', 'Create backend/src/health/learning.ts. Checks: AI Gateway latency for CF Docs enrichment, Sandbox SDK container availability, last successful learning_sessions run timestamp, count of open learning_ai_insight_prs. Register in existing health suite.', 'todo', 'low', 1774835623, 1774835623);

-- ──────────────────────────────────────────────
-- pm_tasks  (43 rows)
-- ──────────────────────────────────────────────
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-001-01-01', 'story-001-01', 'Create sessions.ts — learning_sessions table', 'Fields: id (int PK autoincrement), timestamp (text ISO default), actionTaken (boolean default false), actionRationale (text nullable). Include createSelectSchema + createInsertSchema with .openapi().', 'todo', 'high', 1, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-001-01-02', 'story-001-01', 'Create threads.ts — learning_threads table', 'Fields: id, sessionId FK, timestamp, source enum(jules/stitch/github_pr/github_comment/other), sourceIdentifier (unique), githubRepo. Add unique index on sourceIdentifier for deduplication.', 'todo', 'high', 2, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-001-01-03', 'story-001-01', 'Create messages.ts — learning_messages table', 'Fields: id, sessionId FK, threadId FK, timestamp, author, message, aiAnalysis (nullable, updated post-processing). Add indexes on threadId and sessionId.', 'todo', 'high', 3, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-001-01-04', 'story-001-01', 'Create enrichment.ts — learning_enrichment table', 'Fields: id, messageId FK, timestamp (default now), queryForMcp, mcpResponse (nullable), aiAnalysis (nullable). 1:many per message for multiple CF Docs queries.', 'todo', 'high', 4, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-001-01-05', 'story-001-01', 'Create tagMapping.ts — learning_tag_mapping table', 'IMPORTANT: references existing app/tags.ts (tags.id as text FK). Fields: id, tagId (→ tags.id), messageId FK, rationale. Do NOT create a new learning_tags table.', 'todo', 'high', 5, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-001-01-06', 'story-001-01', 'Create aiInsights.ts — learning_ai_insights table', 'Fields: id, sessionId FK, threadId FK, timestamp, category, insightAnalysis, suggestedImprovement, observedAttemptsReview, status enum(PENDING/IN_VERIFICATION/IMMUNIZED/REVERTED/OBSERVED). Index on category.', 'todo', 'high', 6, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-001-01-07', 'story-001-01', 'Create aiInsightMessages.ts — learning_ai_insight_messages table', 'Links messages to insights for audit traceability. Fields: id, aiInsightId FK, messageId FK, sessionId FK.', 'todo', 'high', 7, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-001-01-08', 'story-001-01', 'Create aiInsightPrs.ts — learning_ai_insight_prs table', 'Tracks PRs submitted to fix flagged issues. Fields: id, sessionId FK, timestamp, repoOwner, repoName, prNumber, prUrl, prDescription, outcome enum(OPEN/MERGED/CLOSED/REVERTED).', 'todo', 'high', 8, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-001-01-09', 'story-001-01', 'Create aiInsightPrMapping.ts — learning_ai_insight_pr_mapping table', 'Links insights to their fix PRs. Fields: id, insightId FK, insightPrId FK, aiRationale, aiSuccessCriteria.', 'todo', 'high', 9, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-001-01-10', 'story-001-01', 'Create aiPrReflections.ts — learning_ai_pr_reflections table', 'Anti-light-switch guard. Fields: id, sessionId FK, newInsightId FK, priorInsightId FK (nullable), insightPrId FK (nullable), agentAnalysis, prSuccessDetermination.', 'todo', 'high', 10, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-001-02-01', 'story-001-02', 'Create learning/index.ts barrel', 'Export all 10 schema files from backend/src/db/schemas/github/learning/index.ts', 'todo', 'high', 1, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-001-02-02', 'story-001-02', 'Update backend/src/db/schemas/github/index.ts', 'Add: export * from ''./learning''', 'todo', 'high', 2, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-001-02-03', 'story-001-02', 'Run D1 migration', 'npm run migrate:db — verify 10 new learning_* tables created in D1 console', 'todo', 'high', 3, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-002-01-01', 'story-002-01', 'Create services/learning/types.ts', 'Define ConversationThread, ConversationMessage, IngestionResult interfaces', 'todo', 'high', 1, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-002-01-02', 'story-002-01', 'Implement Jules ingestion in ingestion.ts', 'Use JulesService.listSessions() from backend/src/services/julius/jules.ts. Map session.name → sourceIdentifier, activities → messages. Skip if sourceIdentifier exists (unique constraint).', 'todo', 'high', 2, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-002-02-01', 'story-002-02', 'Implement GitHub PR ingestion', 'Use getOctokit(env) from backend/src/services/octokit/core.ts. Query: is:pr is:merged author:jmbish04. Fetch PR body + /issues/{n}/comments + /pulls/{n}/comments (review comments). Map to threads + messages.', 'todo', 'high', 1, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-002-03-01', 'story-002-03', 'Implement Stitch ingestion', 'Call Stitch MCP paginated API following pattern from log_conversations.py _sync_stitch method. POST /tools/stitch/scan_conversations_paginated. Map project/screen → thread, prompts → messages.', 'todo', 'medium', 1, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-003-01-01', 'story-003-01', 'Implement enrichMessage tool', 'Generate CF Docs query from message content. Call cloudflare-docs MCP search tool. Insert row into learning_enrichment. Routing through AI Gateway.', 'todo', 'high', 1, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-003-01-02', 'story-003-01', 'Implement tagMessage tool', 'Query existing app.tags table. Select matching tags based on message content. Insert into learning_tag_mapping. If genuinely new category (confirmed by Workers AI) → insert new row into app.tags first.', 'todo', 'high', 2, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-003-01-03', 'story-003-01', 'Implement analyzeMessage tool', 'Workers AI (via AI Gateway): synthesize message + enrichment results + applied tags → update learning_messages.aiAnalysis. Model: @cf/meta/llama-3.1-8b-instruct or claude via AI Gateway.', 'todo', 'high', 3, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-003-02-01', 'story-003-02', 'Implement pattern detection (3-thread threshold)', 'After processing all messages: group by correction category. If same category appears in 3+ distinct threads → call createInsight. Insert learning_ai_insights row (status: PENDING).', 'todo', 'high', 1, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-003-02-02', 'story-003-02', 'Link messages to insights via aiInsightMessages', 'For each new ai_insight: insert rows into learning_ai_insight_messages linking the contributing messages. Required for audit traceability.', 'todo', 'high', 2, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-003-03-01', 'story-003-03', 'Implement contemplateFix tool — Vectorize semantic search', 'Generate embedding for current pattern using @cf/baai/bge-small-en-v1.5. Query VECTORIZE_INDEX (topK: 3). If matches found → mark as repeatOffender.', 'todo', 'high', 1, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-003-03-02', 'story-003-03', 'Implement contemplateFix — D1 prior outcomes check', 'Query learning_ai_pr_reflections for prior entries in same category within last 90 days. If prSuccessDetermination = FAILED → action: UPGRADE_TEMPLATE (target core-github-standardization). Otherwise: SUGGEST_PATCH.', 'todo', 'high', 2, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-003-04-01', 'story-003-04', 'Vectorize filtered messages', 'After analyzeMessage: if message has ai_analysis OR is linked to an ai_insight → generate embedding + insert into VECTORIZE_INDEX. Do not vectorize messages with no analysis.', 'todo', 'medium', 1, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-004-01-01', 'story-004-01', 'Create LearningWorkflow class', 'backend/src/workflows/learning.ts. 4 steps: createSession (insert learning_sessions), ingestConversations (LearningIngestionService), runAnalysis (dispatch LearningAgent DO), finalizeSession (update session actionTaken). Follow health.ts pattern.', 'todo', 'medium', 1, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-004-02-01', 'story-004-02', 'Register LearningWorkflow in wrangler.jsonc', 'Add: { name: ''learning-workflow'', class_name: ''LearningWorkflow'', binding: ''LEARNING_WORKFLOW'' } to workflows array.', 'todo', 'medium', 1, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-004-02-02', 'story-004-02', 'Add daily cron trigger', 'Add ''0 6 * * *'' to triggers.crons in wrangler.jsonc. Wire cron handler to dispatch LearningWorkflow.', 'todo', 'medium', 2, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-005-01-01', 'story-005-01', 'Implement POST /api/learning/sync', 'Dispatch LEARNING_WORKFLOW. Return { workflowRunId, status: ''triggered'' }.', 'todo', 'medium', 1, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-005-01-02', 'story-005-01', 'Implement GET /api/learning/sessions', 'List learning_sessions ordered by timestamp desc, limit 50. Use Zod OpenAPI schema.', 'todo', 'medium', 2, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-005-01-03', 'story-005-01', 'Implement GET /api/learning/insights', 'Filter by category, status, q (like search on insightAnalysis). Ordered by timestamp desc. Use Zod OpenAPI schema.', 'todo', 'medium', 3, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-005-02-01', 'story-005-02', 'Implement GET /api/learning/insights/global', 'Aggregate learning_ai_insights grouped by category. Count IMMUNIZED vs PENDING. Return ''Standardization Score'' per category.', 'todo', 'medium', 1, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-005-02-02', 'story-005-02', 'Implement POST /api/learning/upscale', 'Fetch standardization file contents from core-github-standardization via GitHub API. Start Jules session with context: ''Audit {repoName} against these standards''. Return { julesSessionId }.', 'todo', 'medium', 2, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-006-01-01', 'story-006-01', 'Wire PR webhook handler', 'Add learning-interceptor.ts call in backend/src/automations/pr/ for opened/synchronize events. Extract AI agent author from PR. Scan diff keywords against top learning_ai_insights categories.', 'todo', 'medium', 1, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-006-01-02', 'story-006-01', 'Implement remediation comment posting', 'Use user-persona GH token (GH_TOKEN). Post comment: ''🔍 Pattern analysis detected: {category}. @{agent} please address: {prompt}''. Must use user persona — not app token.', 'todo', 'medium', 2, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-006-02-01', 'story-006-02', 'Implement merge queue logic', 'On PR merged webhook: check learning_ai_insight_prs for matching prUrl. If found and mergeQueueStatus = PENDING_TEMPLATE → trigger Jules session for core-github-standardization update. Update mergeQueueStatus = PROCESSING.', 'todo', 'medium', 1, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-007-01-01', 'story-007-01', 'Build /learning/dashboard Astro page', 'Recharts LineChart showing manual corrections per PR over time vs immunized rules count. Data from GET /api/learning/insights/global. Dark Shadcn theme.', 'todo', 'low', 1, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-007-02-01', 'story-007-02', 'Build /learning/sessions Astro page', 'Shadcn Table with collapsible rows. Columns: date, actionTaken, threadCount, insightCount, prsSubmitted. Expanded: thread list → messages → enrichment docs context.', 'todo', 'low', 1, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-007-03-01', 'story-007-03', 'Build /learning/board Kanban page', 'kibo-ui Kanban board. Columns map to learning_ai_insights.status: PENDING (Detected), IN_VERIFICATION, IMMUNIZED. Cards show category, insightAnalysis, linked PR. Drag → PATCH /api/learning/insights/:id.', 'todo', 'low', 1, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-007-04-01', 'story-007-04', 'Build /learning/showcase standards grid', 'Shadcn Card grid. Fetch standardization file list from GET /repos/jmbish04/core-github-standardization/contents. Each card: filename, last updated, ''View Content'' dialog. ''Upscale Current Repo'' primary button.', 'todo', 'low', 1, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-007-04-02', 'story-007-04', 'Implement Upscale button action', 'Button click → POST /api/learning/upscale with { repoName: activeRepo }. Show loading state → poll Jules session → display implementation plan in Dialog/Sheet.', 'todo', 'low', 2, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-008-01-01', 'story-008-01', 'Create backend/src/health/learning.ts', 'HealthStepResult checks: (1) AI Gateway latency < 2s for CF Docs query, (2) last learning_sessions.timestamp within 25 hours, (3) open learning_ai_insight_prs count < 10. Return health/failure with details.', 'todo', 'low', 1, 1774835623, 1774835623);
INSERT OR IGNORE INTO pm_tasks (id, story_id, title, description, status, priority, "order", created_at, updated_at) VALUES ('task-008-01-02', 'story-008-01', 'Register learning health check in health suite', 'Add checkLearningHealth import to the main health orchestrator. Wire into existing /health route response.', 'todo', 'low', 2, 1774835623, 1774835623);

PRAGMA foreign_keys = ON;

-- ✅ Seed complete: 1 projects, 8 epics, 20 stories, 43 tasks