import { getWebhooksDb } from '@/db';
import { webhookDeliveries } from '@/db/schemas/github/webhooks';
import { desc, gt, and, like } from 'drizzle-orm';
import { createGitHubIssue, createGitHubComment, updateGitHubIssue } from '@/ai/mcp/tools/github/github';
import { HealthStepResult } from '@/health/health-check';
import { getGithubConfig } from '@utils/github/configs';

export async function checkGitHubAPIHealth(env: Env): Promise<HealthStepResult> {
    const start = Date.now();
    const details: any = { api: { status: 'pending', steps: [] } };

    try {
        const apiResult = await runApiChecks(env);
        details.api = apiResult;

        return {
            name: 'GitHub API Lifecycle',
            status: apiResult.status === 'success' ? 'success' : 'failure',
            message: apiResult.status === 'success' ? 'API Operational' : 'API Lifecycle Failed',
            details: details,
            durationMs: Date.now() - start
        };
    } catch (e: any) {
        return {
            name: 'GitHub API Lifecycle',
            status: 'failure',
            message: e.message,
            details: { ...details, stack: e.stack },
            durationMs: Date.now() - start
        };
    }
}

export async function checkWebhooksHealth(env: Env): Promise<HealthStepResult> {
    const start = Date.now();
    const details: any = {
        webhooks: { status: 'pending', gaps: false, verification: 'pending' }
    };

    try {
        const gapCheck = await checkWebhookGaps(env);
        details.webhooks.gaps = gapCheck.hasGaps;
        details.webhooks.lastEvent = gapCheck.lastEvent;

        // Verify recent webhook deliveries from the test repo.
        const webhookVerification = await verifyWebhooks(env);
        details.webhooks.verification = webhookVerification;

        const isHealthy = details.webhooks.verification !== 'failed' && !details.webhooks.gaps;

        return {
            name: 'Webhooks Integration',
            status: isHealthy ? 'success' : 'failure',
            message: isHealthy ? 'Webhooks Operational' : 'Webhook Issues Detected',
            details: details,
            durationMs: Date.now() - start
        };
    } catch (e: any) {
        return {
            name: 'Webhooks Integration',
            status: 'failure',
            message: e.message,
            details: { ...details, stack: e.stack },
            durationMs: Date.now() - start
        };
    }
}

async function checkWebhookGaps(env: Env) {
    const db = getWebhooksDb(env.DB_WEBHOOKS);
    const lastEvents = await db.select().from(webhookDeliveries).orderBy(desc(webhookDeliveries.created_at)).limit(1);
    if (!lastEvents.length) return { hasGaps: true, lastEvent: 'never' };

    const lastDate = new Date(lastEvents[0].created_at!);
    const now = new Date();
    const diffDays = (now.getTime() - lastDate.getTime()) / (1000 * 3600 * 24);

    return { hasGaps: diffDays > 15, lastEvent: lastEvents[0].created_at };
}

async function runApiChecks(env: Env) {
    const owner = getGithubConfig(env, 'owner');
    const repo = env.HEALTH_TEST_REPO_NAME;
    const steps = [];
    let issueNumber: number | null = null;

    try {
        // A. Create Issue
        const title = `Health Check ${new Date().toISOString()}`;
        const issue = await createGitHubIssue(env, owner, repo, title, 'Automated health check running.');
        if (!issue) throw new Error("Failed to create issue");
        steps.push({ step: 'create_issue', status: 'success', id: issue.number });
        issueNumber = issue.number;

        // B. Comment on Issue
        const comment = await createGitHubComment(env, owner, repo, issueNumber, 'Health check comment test.');
        if (!comment) throw new Error("Failed to comment");
        steps.push({ step: 'create_comment', status: 'success', id: comment.id });

        // C. Close Issue
        const closed = await updateGitHubIssue(env, owner, repo, issueNumber, { state: 'closed' });
        if (!closed) throw new Error("Failed to close issue");
        steps.push({ step: 'close_issue', status: 'success' });

        return { status: 'success', steps, issueNumber };

    } catch (e: any) {
        steps.push({ step: 'error', message: e.message });
        return { status: 'failed', steps, issueNumber };
    }
}

async function verifyWebhooks(env: Env) {
    if (!env.HEALTH_TEST_REPO_NAME) return 'skipped';

    const db = getWebhooksDb(env.DB_WEBHOOKS);
    
    // We want to detect webhooks generated by the parallel API test from THIS run.
    // The webhooks take a few seconds to arrive from GitHub. Polling ensures we don't fail-fast.
    // Look for events matching the test repo in the last 60 seconds.
    const recentThreshold = new Date(Date.now() - 60000).toISOString();

    for (let i = 0; i < 8; i++) {
        const logs = await db.select().from(webhookDeliveries)
            .where(and(
                gt(webhookDeliveries.created_at, recentThreshold),
                like(webhookDeliveries.payload, `%${env.HEALTH_TEST_REPO_NAME}%`)
            ))
            .limit(1);

        if (logs.length >= 1) return 'success';
        
        // Wait 2 seconds before polling again
        await new Promise(resolve => setTimeout(resolve, 2000));
    }

    return 'failed';
}
