DROP TABLE `check_run`;--> statement-breakpoint
DROP TABLE `code_scanning_alert`;--> statement-breakpoint
DROP TABLE `commit_comment`;--> statement-breakpoint
DROP TABLE `create`;--> statement-breakpoint
DROP TABLE `custom_property`;--> statement-breakpoint
DROP TABLE `custom_property_values`;--> statement-breakpoint
DROP TABLE `daily_trends`;--> statement-breakpoint
DROP TABLE `delete`;--> statement-breakpoint
DROP TABLE `dependabot_alert`;--> statement-breakpoint
DROP TABLE `dismissal_request_code_scanning`;--> statement-breakpoint
DROP TABLE `dismissal_request_secret_scanning`;--> statement-breakpoint
DROP TABLE `exemption_request_push_ruleset`;--> statement-breakpoint
DROP TABLE `exemption_request_secret_scanning`;--> statement-breakpoint
DROP TABLE `fork`;--> statement-breakpoint
DROP TABLE `issue_comment`;--> statement-breakpoint
DROP TABLE `issues`;--> statement-breakpoint
DROP TABLE `label`;--> statement-breakpoint
DROP TABLE `merge_queue_entry`;--> statement-breakpoint
DROP TABLE `milestone`;--> statement-breakpoint
DROP TABLE `org_block`;--> statement-breakpoint
DROP TABLE `organization_custom_property_values`;--> statement-breakpoint
DROP TABLE `pull_request`;--> statement-breakpoint
DROP TABLE `pull_request_review`;--> statement-breakpoint
DROP TABLE `pull_request_review_comment`;--> statement-breakpoint
DROP TABLE `pull_request_review_thread`;--> statement-breakpoint
DROP TABLE `push`;--> statement-breakpoint
DROP TABLE `repo_analysis`;--> statement-breakpoint
DROP TABLE `repository`;--> statement-breakpoint
DROP TABLE `repository_advisory`;--> statement-breakpoint
DROP TABLE `research_judge_logs`;--> statement-breakpoint
DROP TABLE `searches`;--> statement-breakpoint
DROP TABLE `secret_scanning_alert`;--> statement-breakpoint
DROP TABLE `secret_scanning_alert_location`;--> statement-breakpoint
DROP TABLE `secret_scanning_scan`;--> statement-breakpoint
DROP TABLE `security_advisory`;--> statement-breakpoint
DROP TABLE `security_and_analysis`;--> statement-breakpoint
DROP TABLE `star`;--> statement-breakpoint
DROP TABLE `status`;--> statement-breakpoint
DROP TABLE `sub_issues`;--> statement-breakpoint
DROP TABLE `trending_repos`;--> statement-breakpoint
DROP TABLE `watch`;--> statement-breakpoint
DROP TABLE `webhook_deliveries`;--> statement-breakpoint
DROP TABLE `workflow_dispatch`;--> statement-breakpoint
DROP TABLE `workflow_job`;--> statement-breakpoint
DROP TABLE `workflow_run`;--> statement-breakpoint
DROP TABLE `webhook_configs`;