/**
 * @file backend/src/automations/pr/sentinel-handler.ts
 * @description Sentinel PR Handler — triggered on pull_request.opened and
 * pull_request.synchronize webhook events. Posts a review comment linking
 * matching high-severity AI insights to the PR.
 */

import { Octokit } from '@octokit/rest';
import { getDb } from '@db';
import { learningAiInsights, learningAiInsightPrs } from '@db/schemas/github/learning';
import { and, eq, gte, isNull, or } from 'drizzle-orm';

/**
 * Handles a GitHub pull_request event by:
 * 1. Querying matching open, high-severity insights from D1
 * 2. Posting a Sentinel review comment to the PR
 * 3. Recording the PR link in learning_ai_insight_prs
 *
 * @param event - Raw GitHub webhook payload.
 * @param env - Cloudflare Worker environment bindings.
 */
export async function sentinelPrHandler(event: any, env: Env): Promise<void> {
  const repo = event.repository?.full_name ?? '';
  const prNumber = event.pull_request?.number;

  if (!prNumber || !repo) return;

  const [owner, repoName] = repo.split('/');
  const db = getDb(env.DB);

  // Find open, high-severity insights relevant to this repo (or repoless)
  const insights = await db.select()
    .from(learningAiInsights)
    .where(and(
      or(eq(learningAiInsights.repo, repo), isNull(learningAiInsights.repo)),
      gte(learningAiInsights.severity, 3),
      eq(learningAiInsights.status, 'open'),
    ))
    .limit(5);

  if (insights.length === 0) return;

  // Resolve GitHub token from Secrets Store
  let ghToken: string;
  try {
    ghToken = await (env.GITHUB_PERSONAL_ACCESS_TOKEN as any).get();
  } catch {
    console.error('[SentinelPR] Failed to resolve GITHUB_PERSONAL_ACCESS_TOKEN');
    return;
  }

  const octokit = new Octokit({ auth: ghToken });

  // Build comment body
  const commentLines: string[] = [
    '**[Sentinel Review]** — Patterns detected in this PR matching known failure modes.',
    '',
    '---',
    '',
  ];

  for (const insight of insights) {
    commentLines.push(`### ⚠️ Pattern: \`${insight.patternType}\``);
    commentLines.push(`**${insight.title}**`);
    commentLines.push(`**Severity:** ${insight.severity}/5`);
    commentLines.push(`**Description:** ${insight.description}`);
    commentLines.push('');
    commentLines.push(`> Reference: \`learning_ai_insights#${insight.id}\``);
    commentLines.push('');
    commentLines.push('---');
    commentLines.push('');

    // Record the PR link
    try {
      await db.insert(learningAiInsightPrs).values({
        id: crypto.randomUUID(),
        insightId: insight.id,
        prNumber,
        repo,
        status: 'open',
        createdAt: new Date(),
      });
    } catch (err: any) {
      console.error(`[SentinelPR] Failed to insert insight PR record: ${err.message}`);
    }
  }

  commentLines.push('_This comment was generated by Sentinel. Please resolve before merge._');

  // Post the comment
  try {
    await octokit.issues.createComment({
      owner,
      repo: repoName,
      issue_number: prNumber,
      body: commentLines.join('\n'),
    });
    console.log(`[SentinelPR] Posted review comment on ${repo}#${prNumber}`);
  } catch (err: any) {
    console.error(`[SentinelPR] Failed to post comment on ${repo}#${prNumber}: ${err.message}`);
  }
}
