// env.DB
/**
 * @file schemas/workshop/project_tasks.ts
 * Phased tasks generated by the Workshop Wizard for a given project.
 * These are distinct from the GitHub-linked `tasks` table in projects/tasks.ts.
 */
import { sqliteTable, text, integer } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";
import { workshopProjects } from "./projects";

// --- TypeScript Interfaces for JSON Column ---
export interface Step {
  number: number;
  title: string;
  status: 'not_started' | 'started' | 'blocked' | 'scaffold_complete' | 'pending_success_criteria_signoff' | 'complete';
  technical_requirements: string[];
  success_criteria: string[];
}

export interface Task {
  task_number: number;
  status: 'not_started' | 'started' | 'blocked' | 'scaffold_complete' | 'pending_success_criteria_signoff' | 'complete';
  agent_assigned?: string;
  task_title: string;
  task_description: string;
  task_dependencies: string[];
  cloudflare_docs_queries: string[];
  steps: Step[];
  requirements: string[];
  success_criteria: string[];
}

export interface FileChange {
  action: 'NEW' | 'MODIFY' | 'DELETE';
  file_path: string;
  instructions: string[];
}

export interface ProposedChange {
  category: string;
  files: FileChange[];
}

export interface AutomatedTest {
  command: string;
  expected_outcome: string;
}

export interface ImplementationPlan {
  title: string;
  description: string;
  architecture: {
    explanation: string;
    mermaid_diagram: string;
  };
  proposed_changes: ProposedChange[];
  verification_plan: {
    automated_tests: AutomatedTest[];
    manual_verification: string[];
  };
}

export interface Phase {
  phase_number: number;
  phase_title: string;
  description: string;
  success_criteria: string[];
  implementation_plan: ImplementationPlan;
  tasks: Task[];
}

export const workshopProjectTasks = sqliteTable("workshop_project_tasks", {
    id: text("id").primaryKey(), // UUID
    projectId: text("project_id")
        .notNull()
        .references(() => workshopProjects.id, { onDelete: "cascade" }),
    projectName: text('project_name').notNull(),
    generatedDate: text('generated_date').notNull(),
    totalPhases: integer('total_phases').notNull(),
    phases: text('phases', { mode: 'json' }).$type<Phase[]>().notNull(),
    createdAt: text('created_at').default(sql`CURRENT_TIMESTAMP`).notNull(),
    updatedAt: text('updated_at').default(sql`CURRENT_TIMESTAMP`).notNull()
});
