import { sqliteTable, text, integer, index } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';
import { createInsertSchema, createSelectSchema } from 'drizzle-zod';
import type { z } from 'zod';

export const ACTION_STATUSES = ['pending', 'success', 'error'] as const;
export type ActionStatus = typeof ACTION_STATUSES[number];

export const action_logs = sqliteTable('action_logs', {
  id: text('id').primaryKey(), // UUID
  taskId: text('task_id').notNull(), // UUID generated by the gateway
  actionType: text('action_type').notNull(), // e.g., 'sync_templates', 'deep_research'
  targetRepo: text('target_repo').notNull(),
  status: text('status', { enum: ACTION_STATUSES }).notNull().default('pending'),
  
  // Stored as JSON strings
  requestPayload: text('request_payload'),
  responsePayload: text('response_payload'),

  createdAt: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  updatedAt: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
}, (table) => ({
  taskIdIdx: index('action_logs_task_id_idx').on(table.taskId),
  statusIdx: index('action_logs_status_idx').on(table.status),
  actionTypeIdx: index('action_logs_action_type_idx').on(table.actionType)
}));

export type SelectActionLog = typeof action_logs.$inferSelect;
export type InsertActionLog = typeof action_logs.$inferInsert;

export const InsertActionLogSchema = createInsertSchema(action_logs);
export const SelectActionLogSchema = createSelectSchema(action_logs);
