import type {
  ColbyCommandContext,
  ColbyCommandResult,
  ColbyInvocation,
} from './contracts';
import { prependColbyPrimer } from './primer';
import { findColbyCommand, COLBY_COMMANDS } from './registry';

function formatReplyBody(ctx: ColbyCommandContext, result: ColbyCommandResult, invocation: ColbyInvocation): string {
  const reply = result.body || '';
  const response = ctx.thread.isPullRequest && !result.skipPrimer ? prependColbyPrimer(reply) : reply;

  const tableRows = COLBY_COMMANDS.map(cmd => {
    return `| \`/colby ${cmd.name}\` | ${cmd.description} |`;
  }).join('\n');

  const dynamicHelpMenu = `
<summary><b>Slash Commands Help Menu</b></summary>

| Command | Description |
| --- | --- |
${tableRows}
`;

  const footer = `Generated by \`${invocation.raw}\``;

  return `
${response}

<details>${dynamicHelpMenu}</detail>

---

${footer}`;
}

export async function routeColbyInvocation(
  invocation: ColbyInvocation,
  ctx: ColbyCommandContext,
): Promise<ColbyCommandResult | null> {
  const command = findColbyCommand(invocation.command);
  if (!command) {
    return {
      type: 'reply',
      body: `🤖 Unknown command: \`${invocation.command}\`. Try \`/colby help\`.`,
    };
  }

  if (command.requiresPr && !ctx.thread.isPullRequest) {
    return {
      type: 'reply',
      body: `❌ \`${invocation.command}\` can only be used from a pull request context.`,
    };
  }

  return command.execute(invocation, ctx);
}

export async function handleColbyInvocationAndReply(
  invocation: ColbyInvocation,
  ctx: ColbyCommandContext,
): Promise<ColbyCommandResult | null> {
  // Add eyes reaction to acknowledge command
  if (ctx.thread.commentId) {
    try {
      if (ctx.thread.kind === 'review_comment') {
        await ctx.octokit.rest.reactions.createForPullRequestReviewComment({
          owner: ctx.repo.owner,
          repo: ctx.repo.name,
          comment_id: ctx.thread.commentId,
          content: 'eyes',
        });
      } else {
        await ctx.octokit.rest.reactions.createForIssueComment({
          owner: ctx.repo.owner,
          repo: ctx.repo.name,
          comment_id: ctx.thread.commentId,
          content: 'eyes',
        });
      }
    } catch (e) {
      console.warn("Failed to add eyes reaction", e);
    }
  }

  const result = await routeColbyInvocation(invocation, ctx);
  if (!result || result.type !== 'reply' || !result.body) {
    return result;
  }

  await ctx.octokit.rest.issues.createComment({
    owner: ctx.repo.owner,
    repo: ctx.repo.name,
    issue_number: ctx.thread.number,
    body: formatReplyBody(ctx, result, invocation),
  });

  return result;
}
