import React from 'react';
import { ArrowRight } from 'lucide-react';
import { cn } from '@/lib/utils';

// Define the shape of the plan data based on PlannerAgent's output
interface PlanStep {
    id: string;
    description: string;
    difficulty: 'easy' | 'medium' | 'hard';
    command?: string;
}

interface PlanData {
    title: string;
    steps: PlanStep[];
}

interface PlanCardProps {
    plan: PlanData;
}

export const PlanCard: React.FC<PlanCardProps> = ({ plan }) => {
    return (
        <div className="w-full max-w-2xl bg-card border rounded-xl shadow-sm overflow-hidden my-4">
            {/* Header */}
            <div className="bg-muted/30 p-4 border-b">
                <div className="flex items-center gap-2 mb-1">
                    <div className="p-1 bg-primary/10 rounded">
                        <ArrowRight className="w-4 h-4 text-primary" />
                    </div>
                    <h3 className="font-semibold text-lg text-foreground">Implementation Plan</h3>
                </div>
                <p className="text-muted-foreground text-sm pl-8">{plan.title}</p>
            </div>

            {/* Steps */}
            <div className="divide-y">
                {plan.steps.map((step, index) => (
                    <div key={step.id || index} className="p-4 hover:bg-muted/10 transition-colors group">
                        <div className="flex gap-4">
                            {/* Step Number */}
                            <div className="flex-shrink-0 w-8 h-8 rounded-full bg-secondary flex items-center justify-center text-sm font-medium text-secondary-foreground border">
                                {index + 1}
                            </div>

                            {/* Content */}
                            <div className="flex-1 space-y-2">
                                <div className="flex items-start justify-between gap-4">
                                    <p className="text-sm text-foreground leading-snug font-medium">
                                        {step.description}
                                    </p>
                                    <Badge difficulty={step.difficulty} />
                                </div>

                                {step.command && (
                                    <div className="bg-muted/50 rounded-md p-2 mt-2 font-mono text-xs text-muted-foreground border truncate">
                                        $ {step.command}
                                    </div>
                                )}
                            </div>
                        </div>
                    </div>
                ))}
            </div>

            {/* Footer */}
            <div className="p-3 bg-muted/20 border-t text-xs text-center text-muted-foreground">
                Generated by Planner Agent
            </div>
        </div>
    );
};

const Badge = ({ difficulty }: { difficulty: string }) => {
    const colors = {
        easy: "bg-green-500/10 text-green-600 border-green-200",
        medium: "bg-yellow-500/10 text-yellow-600 border-yellow-200",
        hard: "bg-red-500/10 text-red-600 border-red-200",
    };

    const colorClass = colors[difficulty as keyof typeof colors] || colors.medium;

    return (
        <span className={cn("px-2 py-0.5 rounded-full text-[10px] uppercase font-semibold border tracking-wider", colorClass)}>
            {difficulty}
        </span>
    );
};
